/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'border-strong': '#D0D5DD',
        'on-background': '#141b2c',
        'on-tertiary-fixed-variant': '#7d2d00',
        outline: '#737686',
        'primary-container': '#2563eb',
        background: '#F8F9FB',
        'on-tertiary': '#ffffff',
        'surface-subtle': '#F2F4F7',
        'on-tertiary-container': '#ffede6',
        'error-container': '#ffdad6',
        'secondary-container': '#8a4cfc',
        'on-primary-fixed': '#00174b',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#b4c5ff',
        'surface-dim': '#d2daf0',
        'text-muted': '#667085',
        'text-primary': '#101828',
        'outline-variant': '#c3c6d7',
        success: '#12B76A',
        tertiary: '#943700',
        'on-surface': '#141b2c',
        'on-secondary-fixed': '#25005a',
        'brand-hover': '#1D4ED8',
        'on-tertiary-fixed': '#360f00',
        'inverse-on-surface': '#edf0ff',
        'on-surface-variant': '#434655',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#d2bbff',
        'surface-container-high': '#e0e8ff',
        'tertiary-fixed': '#ffdbcd',
        'brand-soft': '#EFF6FF',
        'surface-container-low': '#f1f3ff',
        surface: '#FFFFFF',
        'tertiary-fixed-dim': '#ffb596',
        'surface-variant': '#dbe2f9',
        'surface-bright': '#f9f9ff',
        'tertiary-container': '#bc4800',
        'surface-tint': '#0053db',
        'on-error-container': '#93000a',
        'voice-soft': '#F5F3FF',
        'primary-fixed': '#dbe1ff',
        'inverse-primary': '#b4c5ff',
        'on-primary-container': '#eeefff',
        error: '#F04438',
        'text-secondary': '#475467',
        'surface-container-highest': '#dbe2f9',
        'on-primary-fixed-variant': '#003ea8',
        'on-error': '#ffffff',
        secondary: '#712ae2',
        border: '#E4E7EC',
        primary: '#004ac6',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#eaddff',
        warning: '#F79009',
        'surface-container': '#e9edff',
        voice: '#7C3AED',
        'inverse-surface': '#293041',
        'on-secondary-fixed-variant': '#5a00c6',
      },
      spacing: {
        'section-desktop': '8.5rem',
        'section-tablet': '5.5rem',
        margin: '1.25rem',
        'space-xs': '0.25rem',
        gutter: '1.5rem',
        'space-lg': '1.5rem',
        'section-mobile': '4.5rem',
        'margin-desktop': '2.5rem',
        'margin-tablet': '2.5rem',
        'space-xl': '2.5rem',
        'gutter-desktop': '2rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        body: ['"Hanken Grotesk"', 'sans-serif'],
        'body-large': ['"Hanken Grotesk"', 'sans-serif'],
        'body-medium': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-h2': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-h2-mobile': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-h3': ['"Hanken Grotesk"', 'sans-serif'],
        'display-hero': ['"Hanken Grotesk"', 'sans-serif'],
        'display-hero-mobile': ['"Hanken Grotesk"', 'sans-serif'],
        metadata: ['"Hanken Grotesk"', 'sans-serif'],
        'label-code': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'body-large': ['19px', { lineHeight: '28px', fontWeight: '400' }],
        'body-medium': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'headline-h3': ['26px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-hero': ['64px', { lineHeight: '68px', letterSpacing: '-0.03em', fontWeight: '700' }],
        body: ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-h2-mobile': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-code': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-hero-mobile': ['40px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-h2': ['44px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '600' }],
        metadata: ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};